#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
session="${TMUX_SESSION:-caer-clean-s42}"
device_ids="${DEVICE_IDS:-0}"
n_gpu="${N_GPU:-1}"
seed="${SEED:-42}"
config="${CONFIG:-configs/experiments/caernet_clean_content_disjoint_exploratory_seed42.json}"
run_id="${RUN_ID:-}"
log_token="${run_id:-$(basename "${config%.json}")__seed${seed}__$(date -u +%Y%m%d_%H%M%S)}"
log_path="artifacts/launch_logs/${log_token}.log"
hsa_override="${HSA_OVERRIDE_GFX_VERSION:-10.3.0}"
rocr_visible_devices="${ROCR_VISIBLE_DEVICES:-$device_ids}"

command -v tmux >/dev/null || {
    echo "tmux is required." >&2
    exit 2
}
if tmux has-session -t "$session" 2>/dev/null; then
    echo "tmux session already exists: $session" >&2
    exit 2
fi

mkdir -p "$repo_root/artifacts/launch_logs"
printf -v accelerator_env 'HSA_OVERRIDE_GFX_VERSION=%q ROCR_VISIBLE_DEVICES=%q ' \
    "$hsa_override" "$rocr_visible_devices"
run_id_arg=""
if [[ -n "$run_id" ]]; then
    printf -v run_id_arg ' --run-id %q' "$run_id"
fi
printf -v launch_command \
    'cd %q && %sPYTHONUNBUFFERED=1 .venv/bin/python run_caer_clean.py train --config %q --seed %q%s --device %q --n-gpu %q --wandb-mode offline > %q 2>&1' \
    "$repo_root" "$accelerator_env" "$config" "$seed" "$run_id_arg" "$device_ids" "$n_gpu" "$log_path"
tmux new-session -d -s "$session" "$launch_command"

echo "Session: $session"
if [[ -n "$run_id" ]]; then
    echo "Run ID: $run_id"
else
    echo "Run ID: generated by run_caer_clean.py from the frozen config variant"
fi
echo "Log: $log_path"
